image: zhemer/alpine_git

Setting tag:
  allow_failure: true
  only:
   changes:
     - kubeinst.yml
  script:
    - |
      v=v`head -1 kubeinst.yml|awk '{print $3}'`
      if [ -z "`git tag|grep $v`" ];then
        git tag $v
        git push --tags https://git-auto-tag-token:$git_auto_tag_token@$CI_SERVER_HOST/$CI_PROJECT_PATH.git HEAD:master
      fi
