# version 0.0.2
# ANSIBLE_DISPLAY_SKIPPED_HOSTS=no ansible-playbook -i vm-centos, -u root -k kubeinst.yml --extra-vars 'worker=true'
# ANSIBLE_DISPLAY_SKIPPED_HOSTS=no ansible-playbook -i localhost, -c local kube_inst.yml 


- name: Deploying Kubernetes cluster on host {{ansible_play_hosts}}
  # gather_facts: no
  hosts: all
  roles:
    - role: role-kubeinst
