# tasks file for kubeinst

# Installing Docker, Kubernetes, initializing master node with metrics-server, Kubernetes dashboard, Helm, nfs-server-provisioner

# - fail: msg='Force exit here {{nfs_server_addr}}'



- name: Get distribution name
  set_fact:
    os: '{{ansible_distribution|lower}}'

# Installing Docker and Kubernetes packages
- name: Docker removing old versions - '{{rm_packages_docker}}'
  package:
    name: '{{rm_packages_docker}}'
    state: absent
  become: yes

- import_tasks: ubuntu.yaml
  when: os == 'debian' or os == 'ubuntu'
- import_tasks: centos.yaml
  when: os == 'redhat' or os == 'centos'

- name: Setting /proc/sys/net/bridge/bridge-nf-call-iptables to 1
  shell: echo 1 >/proc/sys/net/bridge/bridge-nf-call-iptables
  args:
    warn: false
  become: yes

- name: Docker installing packages - '{{inst_packages_docker}}'
  package:
    name: '{{inst_packages_docker}}'
    state: present
    update_cache: yes
  become: yes

- name: Adding current user to docker group
  user:
    name: "{{ lookup('env','USER') }}"
    groups: docker
    append: yes
  become: yes

- name: Kubernetes installing packages - '{{inst_packages}}'
  package:
    name: '{{inst_packages}}'
    state: present
    update_cache: yes
  become: yes

- name: Enabling and running services '{{service_list}}'
  systemd: name='{{item}}' state=started enabled=yes
  with_items: '{{service_list}}'
  become: yes

# Tasks for a worker node
- import_tasks: worker.yaml
  when: worker is defined

# Tasks for a master node
- import_tasks: master.yaml
  when: worker is not defined
